from flask import Flask, request, jsonify, send_file, send_from_directory
from flask_cors import CORS
import os
import uuid
from datetime import datetime
from pptx import Presentation
from pptx.util import Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

app = Flask(__name__, static_folder='../frontend', static_url_path='')
CORS(app)

# Create output folder
OUTPUT_DIR = "ppt_outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

@app.route('/')
def index():
    return send_from_directory('../frontend', 'index.html')

@app.route('/<path:path>')
def serve_static(path):
    return send_from_directory('../frontend', path)

@app.route('/api/generate-outline', methods=['POST'])
def generate_outline():
    try:
        data = request.get_json()
        prompt = data.get('prompt', 'My Presentation')
        num_slides = int(data.get('num_slides', 10))
        
        outline = []
        
        # Title slide
        outline.append({
            "title": prompt,
            "content": ["Welcome to this presentation", "Key topics covered", "What you will learn"]
        })
        
        # Basic slides that work every time
        basic_slides = [
            {"title": "Introduction", "content": ["What is this about?", "Why is it important?", "What will we cover?"]},
            {"title": "Main Concepts", "content": ["Concept 1 explained", "Concept 2 explained", "Concept 3 explained"]},
            {"title": "Key Features", "content": ["Feature 1: Benefits", "Feature 2: Advantages", "Feature 3: Applications"]},
            {"title": "Examples", "content": ["Real-world example 1", "Real-world example 2", "Real-world example 3"]},
            {"title": "Benefits", "content": ["Benefit 1: Time saving", "Benefit 2: Cost effective", "Benefit 3: Easy to use"]},
            {"title": "Challenges", "content": ["Challenge 1 and solution", "Challenge 2 and solution", "Challenge 3 and solution"]},
            {"title": "Best Practices", "content": ["Practice 1: Do this", "Practice 2: Avoid that", "Practice 3: Remember this"]},
            {"title": "Conclusion", "content": ["Summary of key points", "Main takeaways", "Next steps to follow"]}
        ]
        
        # Add slides up to the number requested
        for i in range(min(num_slides - 1, len(basic_slides))):
            outline.append(basic_slides[i])
        
        # Add simple slides if we need more
        while len(outline) < num_slides:
            outline.append({
                "title": f"Additional Point {len(outline)}",
                "content": ["Important point to remember", "Key takeaway here", "Action item to consider"]
            })
        
        print(f"✅ Generated {len(outline)} slides")
        return jsonify({"outline": outline})
        
    except Exception as e:
        print(f"Error: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/api/generate-ppt', methods=['POST'])
def generate_ppt():
    try:
        data = request.get_json()
        outline = data.get('outline', [])
        style = data.get('style', 'professional')
        title = data.get('title', 'Presentation')
        
        # Create presentation
        prs = Presentation()
        
        # Add title slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = title[:100]  # Limit title length
        slide.placeholders[1].text = f"Generated by AI PPT Creator\n{datetime.now().strftime('%B %d, %Y')}"
        
        # Add content slides
        for slide_data in outline:
            # Use bullet layout
            bullet_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_layout)
            
            # Set title (limit length)
            slide.shapes.title.text = slide_data['title'][:80]
            
            # Add bullet points
            content = slide.placeholders[1]
            text_frame = content.text_frame
            text_frame.clear()
            
            for point in slide_data['content'][:5]:  # Max 5 bullet points per slide
                p = text_frame.add_paragraph()
                p.text = str(point)[:200]  # Limit text length
                p.font.size = Pt(20)
                p.space_after = Pt(10)
        
        # Save file
        filename = f"ppt_{uuid.uuid4().hex[:6]}.pptx"
        filepath = os.path.join(OUTPUT_DIR, filename)
        prs.save(filepath)
        
        print(f"✅ Created: {filename}")
        
        return jsonify({
            "download_url": f"/api/download/{filename}",
            "filename": filename
        })
        
    except Exception as e:
        print(f"Error: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/api/download/<filename>', methods=['GET'])
def download_ppt(filename):
    filepath = os.path.join(OUTPUT_DIR, filename)
    if os.path.exists(filepath):
        return send_file(
            filepath,
            as_attachment=True,
            download_name=filename,
            mimetype='application/vnd.openxmlformats-officedocument.presentationml.presentation'
        )
    return jsonify({"error": "File not found"}), 404

if __name__ == '__main__':
    print("\n" + "="*50)
    print("🐰 AI PPT CREATOR - SIMPLE VERSION")
    print("="*50)
    print("✅ Open: http://127.0.0.1:5000")
    print("="*50 + "\n")
    app.run(debug=True, port=5000)