from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
import os
import uuid
from datetime import datetime

app = Flask(__name__)
CORS(app)

# Create output folder
OUTPUT_DIR = "completed_ppts"
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)
    print(f"✅ Created folder: {OUTPUT_DIR}")

@app.route('/api/generate-outline', methods=['POST'])
def generate_outline():
    """Generate presentation outline"""
    try:
        data = request.get_json()
        prompt = data.get('prompt', 'Presentation')
        num_slides = int(data.get('num_slides', 20))
        
        outline = []
        
        # Title slide
        outline.append({
            "title": prompt,
            "content": [
                "Comprehensive Overview",
                "Key Insights & Analysis",
                "Strategic Recommendations",
                "Executive Summary"
            ]
        })
        
        # Content slides
        topics = [
            "Introduction", "Background", "Current Situation", "Key Challenges",
            "Market Analysis", "Competitive Landscape", "Opportunities", "Strategic Framework",
            "Implementation Plan", "Timeline", "Resources Needed", "Team Structure",
            "Risk Management", "Success Metrics", "ROI Analysis", "Case Studies",
            "Best Practices", "Technology Requirements", "Budget Planning", "Next Steps",
            "Conclusion", "Recommendations", "Future Outlook", "Q&A Preparation"
        ]
        
        for i in range(min(num_slides - 1, len(topics))):
            outline.append({
                "title": f"{topics[i]}",
                "content": [
                    f"Overview of {topics[i].lower()} for {prompt}",
                    f"Key factors and considerations",
                    f"Best practices and industry standards",
                    f"Expected outcomes and benefits",
                    f"Actionable recommendations"
                ]
            })
        
        # Add remaining slides if needed
        while len(outline) < num_slides:
            outline.append({
                "title": f"Additional Section {len(outline)}",
                "content": [
                    "Important considerations",
                    "Key takeaways",
                    "Implementation strategies",
                    "Success factors"
                ]
            })
        
        return jsonify({"outline": outline})
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/generate-ppt', methods=['POST'])
def generate_ppt():
    """Generate real PowerPoint file"""
    try:
        data = request.get_json()
        outline = data.get('outline', [])
        style = data.get('style', 'professional')
        title = data.get('title', 'Presentation')
        
        # Create presentation object
        prs = Presentation()
        
        # Style settings
        styles = {
            'professional': {'title_size': 44, 'text_size': 24, 'bold': True},
            'modern': {'title_size': 40, 'text_size': 22, 'bold': False},
            'minimal': {'title_size': 48, 'text_size': 20, 'bold': False},
            'bold': {'title_size': 52, 'text_size': 28, 'bold': True}
        }
        style_settings = styles.get(style, styles['professional'])
        
        # Add title slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title_shape = slide.shapes.title
        subtitle_shape = slide.placeholders[1]
        
        title_shape.text = title
        subtitle_shape.text = f"Generated by AI PPT Creator\n{datetime.now().strftime('%B %d, %Y')}"
        
        # Add content slides
        for slide_data in outline:
            # Use bullet slide layout
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            
            # Set title
            title_shape = slide.shapes.title
            title_shape.text = slide_data['title']
            
            # Set title formatting
            for paragraph in title_shape.text_frame.paragraphs:
                paragraph.font.size = Pt(style_settings['title_size'])
                paragraph.font.bold = style_settings['bold']
                paragraph.font.name = "Arial"
            
            # Add content as bullets
            content_shape = slide.placeholders[1]
            text_frame = content_shape.text_frame
            text_frame.clear()
            
            for point in slide_data['content']:
                p = text_frame.add_paragraph()
                p.text = point
                p.font.size = Pt(style_settings['text_size'])
                p.font.name = "Arial"
                p.level = 0
                p.space_after = Pt(12)
        
        # Generate unique filename
        unique_id = uuid.uuid4().hex[:8]
        filename = f"presentation_{unique_id}.pptx"
        filepath = os.path.join(OUTPUT_DIR, filename)
        
        # Save the presentation
        prs.save(filepath)
        
        # Verify file was created
        if os.path.exists(filepath):
            file_size = os.path.getsize(filepath)
            print(f"✅ PPT created: {filename} ({file_size} bytes)")
            
            return jsonify({
                "success": True,
                "download_url": f"/api/download/{filename}",
                "filename": filename,
                "message": "Presentation generated successfully"
            })
        else:
            raise Exception("File was not created")
            
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        return jsonify({"error": str(e)}), 500

@app.route('/api/download/<filename>', methods=['GET'])
def download_ppt(filename):
    """Download the PowerPoint file"""
    try:
        # Security: only allow alphanumeric, dash, underscore
        import re
        if not re.match(r'^[a-zA-Z0-9_-]+\.pptx$', filename):
            return jsonify({"error": "Invalid filename"}), 400
        
        filepath = os.path.join(OUTPUT_DIR, filename)
        
        print(f"📥 Download request for: {filename}")
        print(f"📁 Looking for: {filepath}")
        
        if os.path.exists(filepath):
            print(f"✅ File found, sending download...")
            return send_file(
                filepath,
                as_attachment=True,
                download_name=filename,
                mimetype='application/vnd.openxmlformats-officedocument.presentationml.presentation'
            )
        else:
            print(f"❌ File not found: {filepath}")
            # List available files for debugging
            files = os.listdir(OUTPUT_DIR) if os.path.exists(OUTPUT_DIR) else []
            return jsonify({
                "error": f"File '{filename}' not found",
                "available_files": files,
                "output_directory": OUTPUT_DIR
            }), 404
            
    except Exception as e:
        print(f"❌ Download error: {str(e)}")
        return jsonify({"error": str(e)}), 500

@app.route('/api/list-files', methods=['GET'])
def list_files():
    """List all generated PPT files"""
    try:
        files = os.listdir(OUTPUT_DIR) if os.path.exists(OUTPUT_DIR) else []
        return jsonify({
            "files": files,
            "count": len(files),
            "directory": OUTPUT_DIR
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/health', methods=['GET'])
def health():
    """Health check"""
    files = os.listdir(OUTPUT_DIR) if os.path.exists(OUTPUT_DIR) else []
    return jsonify({
        "status": "running",
        "message": "Server is working!",
        "output_folder": OUTPUT_DIR,
        "files_count": len(files)
    })

if __name__ == '__main__':
    print("\n" + "="*70)
    print("🎯 AI PPT CREATOR - WORKING VERSION WITH REAL PPTX")
    print("="*70)
    print(f"✅ Server: http://127.0.0.1:5000")
    print(f"✅ Output folder: {OUTPUT_DIR}")
    print(f"✅ Health check: http://127.0.0.1:5000/api/health")
    print(f"✅ List files: http://127.0.0.1:5000/api/list-files")
    print("="*70)
    print("\n🚀 Server is ready! Open http://127.0.0.1:5000\n")
    app.run(debug=True, port=5000, host='127.0.0.1')