from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
import os

class PPTGenerator:
    def __init__(self):
        self.styles = {
            'professional': {
                'title_color': RGBColor(0, 0, 0),
                'text_color': RGBColor(50, 50, 50),
                'bg_color': RGBColor(255, 255, 255),
                'font_name': 'Arial',
                'title_size': 44,
                'text_size': 24
            },
            'modern': {
                'title_color': RGBColor(0, 0, 0),
                'text_color': RGBColor(30, 30, 30),
                'bg_color': RGBColor(245, 245, 245),
                'font_name': 'Calibri',
                'title_size': 40,
                'text_size': 22
            },
            'minimal': {
                'title_color': RGBColor(0, 0, 0),
                'text_color': RGBColor(20, 20, 20),
                'bg_color': RGBColor(255, 255, 255),
                'font_name': 'Helvetica',
                'title_size': 48,
                'text_size': 20
            },
            'bold': {
                'title_color': RGBColor(0, 0, 0),
                'text_color': RGBColor(0, 0, 0),
                'bg_color': RGBColor(240, 240, 240),
                'font_name': 'Impact',
                'title_size': 52,
                'text_size': 28
            }
        }
    
    def create_presentation(self, outline, output_path, style='professional', title='Presentation'):
        """Create PowerPoint presentation from outline"""
        prs = Presentation()
        
        # Get style settings
        style_settings = self.styles.get(style, self.styles['professional'])
        
        # Create title slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title_shape = slide.shapes.title
        subtitle_shape = slide.placeholders[1]
        
        title_shape.text = title
        subtitle_shape.text = f"Generated by AI PPT Creator\n{__import__('datetime').datetime.now().strftime('%B %d, %Y')}"
        
        # Create content slides
        for slide_data in outline:
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            
            # Set title
            title_shape = slide.shapes.title
            title_shape.text = slide_data['title']
            for paragraph in title_shape.text_frame.paragraphs:
                paragraph.font.size = Pt(style_settings['title_size'])
                paragraph.font.bold = True
                paragraph.font.name = style_settings['font_name']
            
            # Set content
            content_shape = slide.placeholders[1]
            text_frame = content_shape.text_frame
            text_frame.clear()
            
            for point in slide_data['content']:
                p = text_frame.add_paragraph()
                p.text = point
                p.font.size = Pt(style_settings['text_size'])
                p.font.name = style_settings['font_name']
                p.font.color.rgb = style_settings['text_color']
                p.level = 0
                p.space_after = Pt(12)
        
        # Save presentation
        prs.save(output_path)
        return output_path